# SPDX-License-Identifier: GPL-2.0

ccflags-y += -I$(src)

obj-$(CONFIG_NET_SCH_MQPRIO) += sch_mqprio.o
sch_mqprio-objs += sch_mqprio.o sch_mqprio_lib.o

obj-$(CONFIG_NET_SCH_CBS) += sch_cbs.o

obj-$(CONFIG_NET_CLS_FLOWER) += cls_flower.o

obj-$(CONFIG_NET_SCH_ETF) += sch_etf.o

