# SPDX-License-Identifier: GPL-2.0

ccflags-y += -I$(src)

obj-$(CONFIG_SCSI_UFS_CRYPTO_QTI) += ufshcd-crypto-qti.o

obj-$(CONFIG_SCSI_UFS_QCOM) += ufs-qcom.o

obj-$(CONFIG_SCSI_UFS_QCOM_SCMI) += ufs-qcom-scmi.o

