# SPDX-License-Identifier: GPL-2.0

ccflags-y += -I$(src)

obj-$(CONFIG_QCOM_BAM_DMA) += bam_dma.o

obj-$(CONFIG_MSM_GPI_DMA) += msm_gpi.o

obj-$(CONFIG_QCOM_GPI_DMA) += gpi.o
gpi-objs += gpi_fixed.o

