# SPDX-License-Identifier: GPL-2.0

ccflags-y += -I$(src)

obj-$(CONFIG_PCS_XPCS) += pcs-xpcs.o
pcs-xpcs-objs += pcs-xpcs-plat.o pcs-xpcs-nxp.o pcs-xpcs-wx.o pcs-xpcs.o

obj-$(CONFIG_PCS_QCOM) += pcs-xpcs-qcom.o

