/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
 */

#ifndef _DPD_PROXY_H
#define _DPD_PROXY_H

#include <linux/types.h>
#include <linux/scatterlist.h>
#include <linux/qtee_shmbridge.h>
#include <linux/firmware/qcom/si_object.h>
#include <linux/atomic.h>
#include <linux/completion.h>

/*
 * Service Interface Definitions - ISecureMemoryManager
 * ----------------------------------------------------
 */
#define CSecureMemoryManager_UID (448)

/*
 * MapMemory service call:
 * Input buffer: struct imm_map_cmd[]
 * Input object: memory object
 */
#define IMM_SVC_MAP (0)
#define IMM_F_READ BIT(0)
#define IMM_F_WRITE BIT(1)
#define IMM_VALID_FLAGS GENMASK(1, 0)

struct imm_map_cmd {
	u32 eVM;
	u32 flags;
	u64 iova;
	u64 size;
	u64 offset;
} __packed;

/*
 * UnmapMemory service call:
 * Input buffer: struct imm_unmap_cmd
 * Input object: memory object
 *
 * Note: In the TEE service, this structure is defined inline
 * in an autogenerated function 'IMemoryManager_DEFINE_INVOKE'.
 */
#define IMM_SVC_UNMAP (1)

struct imm_unmap_cmd {
	u64 iova;
	u64 size;
	u32 eVM;
} __packed;

/*
 * Linux Interface
 * ---------------
 */

struct dpd_scatterlist {
	struct si_object *shm;
	unsigned int nents_in_mt;
	struct sg_table sgt;
	size_t size;
	atomic_t mapcount;
	struct completion done;
	struct rcu_head rcu;
};

int dpd_svc_map(struct dpd_scatterlist *dpd_sg, u32 domain, u32 flags, u64 iova);
int dpd_svc_unmap(struct dpd_scatterlist *dpd_sg, u32 domain, u64 iova);
int dpd_proxy_available(void);
struct dpd_scatterlist *dpd_mtree_lookup(unsigned long pfn);
#endif /* _DPD_PROXY_H */
