# SPDX-License-Identifier: GPL-2.0

ccflags-y += -I$(src)

obj-$(CONFIG_VIRTIO_MEM) += virtio_mem.o
virtio_mem-objs += virtio_mem.o qti_virtio_mem.o

obj-$(CONFIG_VIRTIO_MMIO) += virtio_mmio.o

obj-$(CONFIG_VIRTIO_INPUT) += virtio_input.o

