# SPDX-License-Identifier: GPL-2.0

ccflags-y += -I$(src)

obj-$(CONFIG_PINCTRL_CANOE) += pinctrl-canoe.o

obj-$(CONFIG_PINCTRL_MSM) += pinctrl-msm.o

obj-$(CONFIG_PINCTRL_SCUBA) += pinctrl-scuba.o

obj-$(CONFIG_PINCTRL_QCOM_SPMI_PMIC) += pinctrl-spmi-gpio.o

obj-$(CONFIG_PINCTRL_QCOM_SPMI_PMIC) += pinctrl-spmi-mpp.o

obj-$(CONFIG_PINCTRL_RAVELIN) += pinctrl-ravelin.o

obj-$(CONFIG_PINCTRL_BOURTZI) += pinctrl-bourtzi.o

obj-$(CONFIG_PINCTRL_SUN) += pinctrl-sun.o

obj-$(CONFIG_PINCTRL_VIENNA) += pinctrl-vienna.o

obj-$(CONFIG_PINCTRL_ALOR) += pinctrl-alor.o

obj-$(CONFIG_PINCTRL_CHORA) += pinctrl-chora.o

obj-$(CONFIG_PINCTRL_YUPIK) += pinctrl-yupik.o

obj-$(CONFIG_PINCTRL_LAHAINA) += pinctrl-lahaina.o

obj-$(CONFIG_PINCTRL_KHAJE) += pinctrl-khaje.o

obj-$(CONFIG_PINCTRL_BENGAL) += pinctrl-bengal.o

obj-$(CONFIG_PINCTRL_MONACO) += pinctrl-monaco.o

obj-$(CONFIG_PINCTRL_MALABAR) += pinctrl-malabar.o

obj-$(CONFIG_PINCTRL_DIREWOLF) += pinctrl-direwolf.o

obj-$(CONFIG_PINCTRL_LEMANS) += pinctrl-lemans.o

obj-$(CONFIG_PINCTRL_X1E80100) += pinctrl-x1e80100.o

obj-$(CONFIG_PINCTRL_MONACO_AUTO) += pinctrl-monaco_auto.o

obj-$(CONFIG_PINCTRL_SA8797P) += pinctrl-sa8797p.o

obj-$(CONFIG_PINCTRL_PIKACHU) += pinctrl-pikachu.o

obj-$(CONFIG_PINCTRL_SHIKRA) += pinctrl-shikra.o

obj-$(CONFIG_PINCTRL_GLYMUR) += pinctrl-glymur.o

obj-$(CONFIG_PINCTRL_SERAPH) += pinctrl-seraph.o

