/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
 */

#ifndef _DPD_PROXY_INTERNAL_H
#define _DPD_PROXY_INTERNAL_H

/*
 * Service Interface Definitions - ISecureMemoryManager
 * ----------------------------------------------------
 */
#define CSecureMemoryManager_UID (448)

/*
 * MapMemory service call:
 * Input buffer: struct imm_map_cmd[]
 * Input object: memory object
 */
#define IMM_SVC_MAP (0)
#define IMM_F_READ BIT(0)
#define IMM_F_WRITE BIT(1)
#define IMM_VALID_FLAGS GENMASK(1, 0)

struct imm_map_cmd {
	u32 eVM;
	u32 flags;
	u64 iova;
	u64 size;
	u64 offset;
} __packed;

/*
 * UnmapMemory service call:
 * Input buffer: struct imm_unmap_cmd
 * Input object: memory object
 *
 * Note: In the TEE service, this structure is defined inline
 * in an autogenerated function 'IMemoryManager_DEFINE_INVOKE'.
 */
#define IMM_SVC_UNMAP (1)

struct imm_unmap_cmd {
	u64 iova;
	u64 size;
	u32 eVM;
} __packed;

#endif /* _DPD_PROXY_INTERNAL_H */
