# SPDX-License-Identifier: GPL-2.0

ccflags-y += -I$(src)

obj-$(CONFIG_QCOM_PIL_INFO) += qcom_pil_info.o

obj-$(CONFIG_QCOM_Q6V5_COMMON) += qcom_q6v5.o

obj-$(CONFIG_QCOM_Q6V5_PAS) += qcom_q6v5_pas.o

obj-$(CONFIG_QCOM_SPSS) += qcom_spss.o

obj-$(CONFIG_QCOM_SYSMON) += qcom_sysmon.o

obj-$(CONFIG_QCOM_RPROC_COMMON) += rproc_qcom_common.o
rproc_qcom_common-objs += qcom_common.o qcom_tracepoints.o

