# SPDX-License-Identifier: GPL-2.0

ccflags-y += -I$(src)

obj-$(CONFIG_QCOM_LLCC_PMU) += qcom_llcc_pmu.o

obj-$(CONFIG_ARM_SMMU_PMU) += arm_smmu_pmu.o

obj-$(CONFIG_MSM_DWC_PCIE_PMU) += dwc_pcie_pmu.o

