# SPDX-License-Identifier: GPL-2.0


# Subdirectories
obj-y += dwc3/
obj-y += gadget/function/
obj-y += misc/
obj-y += pd/
obj-y += phy/
obj-y += redriver/
obj-y += repeater/
obj-y += typec/mux/
obj-y += typec/ucsi/

