# SPDX-License-Identifier: GPL-2.0

ccflags-y += -I$(src)

obj-$(CONFIG_POWER_RESET_QCOM_DOWNLOAD_MODE) += qcom-dload-mode.o

obj-$(CONFIG_POWER_RESET_QCOM_PON) += qcom-pon.o

obj-$(CONFIG_POWER_RESET_QCOM_REBOOT_REASON) += qcom-reboot-reason.o

obj-$(CONFIG_REBOOT_MODE) += reboot-mode.o

obj-$(CONFIG_POWER_RESET_QCOM) += msm-poweroff.o

obj-$(CONFIG_POWER_RESET_QCOM_VM) += msm-vm-poweroff.o

