# SPDX-License-Identifier: GPL-2.0

ccflags-y += -I$(src)

obj-$(CONFIG_MFD_I2C_PMIC) += qcom-i2c-pmic.o

obj-$(CONFIG_MFD_SPMI_PMIC) += qcom-spmi-pmic.o

obj-$(CONFIG_MFD_QCOM_PM8008) += qcom-pm8008.o

