# SPDX-License-Identifier: GPL-2.0

ccflags-y += -I$(src)

obj-$(CONFIG_Q2SPI_MSM_GENI) += q2spi-geni.o
q2spi-geni-objs += q2spi-gsi.o q2spi-msm-geni.o

obj-$(CONFIG_SPI_MSM_GENI) += spi-msm-geni.o

obj-$(CONFIG_SPI_QCOM_GENI) += spi-geni-qcom.o

obj-$(CONFIG_SPI_QCOM_GENI_MSM) += spi-geni-qcom-msm.o

