# SPDX-License-Identifier: GPL-2.0

ccflags-y += -I$(src)

obj-$(CONFIG_I2C_MSM_GENI) += i2c-msm-geni.o

obj-$(CONFIG_I2C_QCOM_GENI_MSM) += i2c-qcom-geni-msm.o

obj-$(CONFIG_I2C_QCOM_GENI) += i2c-qcom-geni.o

obj-$(CONFIG_I2C_VIRTIO) += i2c-virtio.o

