# SPDX-License-Identifier: GPL-2.0

ccflags-y += -I$(src)

obj-$(CONFIG_NOP_USB_XCEIV) += phy-generic.o

obj-$(CONFIG_USB_M31_MSM_EUSB2_PHY) += phy-msm-m31-eusb2.o

obj-$(CONFIG_USB_MSM_SSPHY_QMP) += phy-msm-ssusb-qmp.o

obj-$(CONFIG_USB_QCOM_EMU_PHY) += phy-qcom-emu.o

obj-$(CONFIG_MSM_HSUSB_PHY) += phy-msm-snps-hs.o

obj-$(CONFIG_MSM_QUSB_PHY) += phy-msm-qusb.o

obj-$(CONFIG_MSM_QUSB_PHY) += phy-msm-qusb-v2.o

obj-$(CONFIG_USB_MSM_EUSB2_PHY) += phy-msm-snps-eusb2.o

